cnss2: modification for gcc-13.3 and CLD compling
The modification is used to address build issue on x86 ubuntu with gcc
13.3.0 and kernel 6.18

typical build errors:
error: no previous prototype for ‘cnss_remove’
error: implicit conversion from ‘enum cnss_driver_mode’ to
‘enum wlfw_driver_mode_enum_v01’ [-Werror=enum-conversion]
error: this statement may fall through [-Werror=implicit-fallthrough=]

add missing api which used in CLD driver

Change-Id: Ieb2024e332f18fc16af48ded118aebc1e223bb59
Signed-off-by: Ming Jiang <mjiang@qti.qualcomm.com>
CRs-Fixed: 4373208